# Generated by Django 6.1.1 on 2026-09-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline_name',
            field=models.TextField(verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.discipline'),
        ),
    ]
