# Generated by Django 6.1.1 on 2026-09-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_discipline_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='discipline_name',
        ),
    ]
