# Generated by Django 6.1.1 on 2026-09-22 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_discipline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('social_media', models.TextField(verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('country', models.TextField(verbose_name='Страна')),
                ('founded_year', models.PositiveIntegerField(verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='genre',
            field=models.TextField(blank=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Призовой фонд'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.organizer', verbose_name='Организатор'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
                ('real_name', models.TextField(verbose_name='Настоящее имя')),
                ('role', models.CharField(choices=[('player', 'Игрок'), ('admin', 'Администратор')], default='player', max_length=16, verbose_name='Роль')),
                ('game_role', models.TextField(blank=True, verbose_name='Игровая роль')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Контактная почта')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.team', verbose_name='Команда')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
