# Generated by Django 6.1.1 on 2026-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_organizer_team_discipline_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='disciplines', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='organizers', verbose_name='Логотип организатора'),
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='teams', verbose_name='Логотип команды'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Аватар'),
        ),
    ]
