# Generated by Django 6.1.1 on 2026-09-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='opt_key',
            field=models.CharField(blank=True, max_length=32, verbose_name='Ключ двухфакторной аутентификации'),
        ),
    ]
