# Generated by Django 6.1.1 on 2026-09-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_userprofile_opt_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='opt_key',
            new_name='otp_key',
        ),
    ]
