# Generated by Django 6.1.1 on 2026-09-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_rename_opt_key_userprofile_otp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='tournaments.userprofile', verbose_name='Капитан'),
        ),
    ]
