# Generated by Django 6.1.1 on 2026-09-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registration', 'Регистрация открыта'), ('closed', 'Регистрация закрыта'), ('ongoing', 'Проводится'), ('finished', 'Завершён')], default='registration', max_length=16, verbose_name='Статус турнира'),
        ),
    ]
