# Generated by Django 6.1.1 on 2026-09-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournamentapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Капитан команды'),
        ),
    ]
